spring:
  cloud:
    gateway:
      routes:
        - id: baidu-route
          uri: https://wwww.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq-route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq